steps:
  - step: &build_ios
      name: Build iOS
      image: felhr85/docker-for-ios-bitbucket-pipelines:latest
      script:
        - bash pipelines_server.sh 
pipelines:
  branches:
    master:
      - step: *build_ios    